// AUTO-GENERATED by scripts/generate-template-registry.ts — do not edit by hand.
// Run `bun run gen:templates` after adding or changing a template folder.
import type { ScreenTemplateEntry } from "./types";
import { meta as cardGrid } from "./card-grid/meta";
import { meta as chat } from "./chat/meta";
import { meta as dashboard } from "./dashboard/meta";
import { meta as detailHero } from "./detail-hero/meta";
import { meta as error } from "./error/meta";
import { meta as form } from "./form/meta";
import { meta as list } from "./list/meta";
import { meta as notifications } from "./notifications/meta";
import { meta as pricing } from "./pricing/meta";
import { meta as profile } from "./profile/meta";
import { meta as search } from "./search/meta";
import { meta as settings } from "./settings/meta";
import { meta as welcome } from "./welcome/meta";

/** Screen templates collected from client/templates/*\/meta.ts, sorted by order then id. */
export const SCREEN_TEMPLATES: ScreenTemplateEntry[] = [
  cardGrid,
  chat,
  dashboard,
  detailHero,
  error,
  form,
  list,
  notifications,
  pricing,
  profile,
  search,
  settings,
  welcome,
].sort((a, b) => a.order - b.order || a.id.localeCompare(b.id));
