const { withAppDelegate, withInfoPlist, withXcodeProject, IOSConfig } = require("expo/config-plugins");
const fs = require("node:fs");
const path = require("node:path");

// Adopts the UIScene life cycle in the generated iOS project. The iOS 27 SDK
// (Xcode 27) refuses to launch apps that still use the AppDelegate/window life
// cycle ("UIScene life cycle is required for apps built with this SDK", TN3187),
// but Expo's scene support landed on main after the sdk-57 branch cut and is not
// in any stable 57.0.x release (expo/expo#46664, #47570).
//
// This plugin backports that fix: it vendors a SceneDelegate (a copy of the
// canary's ExpoAppSceneDelegate + ExpoReactNativeFactoryProvider), registers it
// in the Xcode project, adds the UIApplicationSceneManifest to Info.plist, and
// rewrites the template AppDelegate so the scene delegate owns the window.
//
// It self-disables once the installed `expo` package ships ExpoAppSceneDelegate,
// so it is safe to leave in place across the SDK upgrade that fixes this.
// Portable: drop this file into any bare/CNG Expo SDK 57 project's plugins/
// directory and add it to `plugins` in the app config.

const SCENE_DELEGATE_FILE = "SceneDelegate.swift";

const SCENE_DELEGATE_SOURCE = `// @generated by plugins/withIosSceneLifecycle.js — do not edit.
// Vendored from expo@57.0.0-canary-20260720-b6d63bc (ExpoAppSceneDelegate +
// ExpoReactNativeFactoryProvider), which is not in SDK 57.0.x. The iOS 27 SDK
// requires the UIScene life cycle (TN3187); the plugin stops generating this
// file once the installed expo package ships scene support (expo/expo#46664).

import Foundation
internal import Expo
internal import ExpoModulesCore
import React

protocol ExpoReactNativeFactoryProvider: AnyObject {
  var window: UIWindow? { get set }
  var reactNativeFactory: RCTReactNativeFactory? { get }
  var reactNativeFactoryModuleName: String { get }
}

extension ExpoReactNativeFactoryProvider {
  var reactNativeFactoryModuleName: String {
    return "main"
  }
}

@available(iOSApplicationExtension, unavailable)
@objc(SceneDelegate)
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene else {
      return
    }
    guard let provider = UIApplication.shared.delegate as? ExpoReactNativeFactoryProvider,
      let factory = provider.reactNativeFactory else {
      fatalError(
        "SceneDelegate couldn't start React Native because the app delegate doesn't provide a "
        + "React Native factory. Make sure your AppDelegate conforms to ExpoReactNativeFactoryProvider and "
        + "creates its RCTReactNativeFactory in application(_:didFinishLaunchingWithOptions:)."
      )
    }

    let window = UIWindow(windowScene: windowScene)
    self.window = window

    // Mirror the window onto the app delegate so code that reads
    // \`UIApplication.shared.delegate?.window\` keeps working (e.g. expo-system-ui).
    provider.window = window

    // Under the scene life cycle UIKit passes cold-start URLs and activities in \`connectionOptions\`
    // rather than in the app delegate's launch options. React Native's \`Linking.getInitialURL()\`
    // only reads them from launch options, so rebuild them here; otherwise a link that cold-starts
    // the app is delivered to no one, because the \`url\` event routed below fires before JS is ready.
    let browsingWebActivity = connectionOptions.userActivities.first {
      $0.activityType == NSUserActivityTypeBrowsingWeb
    }
    factory.startReactNative(
      withModuleName: provider.reactNativeFactoryModuleName,
      in: window,
      launchOptions: Self.launchOptions(
        url: connectionOptions.urlContexts.first?.url,
        userActivity: browsingWebActivity
      )
    )

    // Deep links / universal links.
    Self.route(urlContexts: connectionOptions.urlContexts)
    connectionOptions.userActivities.forEach { Self.route(userActivity: $0) }
  }

  func sceneDidDisconnect(_ scene: UIScene) {
    window = nil
  }

  // In the scene lifecycle UIKit no longer calls the app delegate equivalents, so we forward
  // these to the subscriber manager to preserve existing subscriber behavior.

  func sceneDidBecomeActive(_ scene: UIScene) {
    ExpoAppDelegateSubscriberManager.applicationDidBecomeActive(UIApplication.shared)
  }

  func sceneWillResignActive(_ scene: UIScene) {
    ExpoAppDelegateSubscriberManager.applicationWillResignActive(UIApplication.shared)
  }

  func sceneWillEnterForeground(_ scene: UIScene) {
    ExpoAppDelegateSubscriberManager.applicationWillEnterForeground(UIApplication.shared)
  }

  func sceneDidEnterBackground(_ scene: UIScene) {
    ExpoAppDelegateSubscriberManager.applicationDidEnterBackground(UIApplication.shared)
  }

  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    Self.route(urlContexts: URLContexts)
  }

  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    Self.route(userActivity: userActivity)
  }
}

// MARK: - Launch options & routing helpers

@available(iOSApplicationExtension, unavailable)
extension SceneDelegate {
  /// Rebuilds the launch options that \`Linking.getInitialURL()\` reads from a scene's connection
  /// options. Returns \`nil\` when the app wasn't cold-started by a URL or a browsing-web activity,
  /// so it can be forwarded to \`startReactNative\` as-is.
  static func launchOptions(
    url: URL?,
    userActivity: NSUserActivity?
  ) -> [UIApplication.LaunchOptionsKey: Any]? {
    // Build the keys from their underlying constant strings rather than the \`UIApplication\`
    // accessors (\`.url\`, \`.userActivityDictionary\`): those accessors are deprecated as of iOS 26
    // in favor of the scene APIs, but React Native's \`getInitialURL\` still reads the launch options
    // by these exact keys, so this is the shape it expects.
    var launchOptions: [UIApplication.LaunchOptionsKey: Any] = [:]
    if let url {
      let urlKey = UIApplication.LaunchOptionsKey(rawValue: "UIApplicationLaunchOptionsURLKey")
      launchOptions[urlKey] = url
    }
    if let userActivity {
      let userActivityDictionaryKey = UIApplication.LaunchOptionsKey(
        rawValue: "UIApplicationLaunchOptionsUserActivityDictionaryKey"
      )
      launchOptions[userActivityDictionaryKey] = [
        "UIApplicationLaunchOptionsUserActivityTypeKey": userActivity.activityType,
        "UIApplicationLaunchOptionsUserActivityKey": userActivity,
      ]
    }
    return launchOptions.isEmpty ? nil : launchOptions
  }

  /// Pass incoming URL contexts to both the subscriber manager and \`RCTLinkingManager\`.
  static func route(urlContexts: Set<UIOpenURLContext>) {
    for context in urlContexts {
      let options = openURLOptions(from: context.options)
      _ = ExpoAppDelegateSubscriberManager.application(UIApplication.shared, open: context.url, options: options)
      RCTLinkingManager.application(UIApplication.shared, open: context.url, options: options)
    }
  }

  /// Passes an incoming \`NSUserActivity\` to both the subscriber manager and \`RCTLinkingManager\`.
  static func route(userActivity: NSUserActivity) {
    _ = ExpoAppDelegateSubscriberManager.application(
      UIApplication.shared,
      continue: userActivity,
      restorationHandler: { _ in }
    )
    RCTLinkingManager.application(
      UIApplication.shared,
      continue: userActivity,
      restorationHandler: { _ in }
    )
  }

  private static func openURLOptions(
    from sceneOptions: UIScene.OpenURLOptions
  ) -> [UIApplication.OpenURLOptionsKey: Any] {
    var options: [UIApplication.OpenURLOptionsKey: Any] = [:]
    if let sourceApplication = sceneOptions.sourceApplication {
      options[.sourceApplication] = sourceApplication
    }
    if let annotation = sceneOptions.annotation {
      options[.annotation] = annotation
    }
    options[.openInPlace] = sceneOptions.openInPlace
    return options
  }
}
`;

const SCENE_MANIFEST = {
  UIApplicationSupportsMultipleScenes: false,
  UISceneConfigurations: {
    UIWindowSceneSessionRoleApplication: [
      {
        UISceneConfigurationName: "Default Configuration",
        UISceneDelegateClassName: "$(PRODUCT_MODULE_NAME).SceneDelegate",
      },
    ],
  },
};

// Once the installed expo package ships its own scene support, the template
// AppDelegate will adopt it during prebuild and this backport must step aside.
function expoShipsSceneSupport(projectRoot) {
  try {
    const expoPackageDir = path.dirname(
      require.resolve("expo/package.json", { paths: [projectRoot] }),
    );
    return fs.existsSync(
      path.join(expoPackageDir, "ios", "AppDelegates", "ExpoAppSceneDelegate.swift"),
    );
  } catch {
    return false;
  }
}

function rewriteAppDelegate(contents) {
  if (contents.includes("ExpoReactNativeFactoryProvider")) {
    return contents; // already rewritten (or the upstream template took over)
  }

  const withConformance = contents.replace(
    /class AppDelegate:\s*ExpoAppDelegate\s*\{/,
    "class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider {",
  );
  if (withConformance === contents) {
    throw new Error(
      "withIosSceneLifecycle: could not find `class AppDelegate: ExpoAppDelegate {` in AppDelegate.swift. " +
        "The template may have changed; update plugins/withIosSceneLifecycle.js or remove it if expo now " +
        "ships UIScene support.",
    );
  }

  const windowBlock =
    /#if os\(iOS\) \|\| os\(tvOS\)\s*\n\s*window = UIWindow\(frame: UIScreen\.main\.bounds\)\s*\n\s*factory\.startReactNative\([\s\S]*?\)\s*\n#endif\s*\n/;
  if (!windowBlock.test(withConformance)) {
    throw new Error(
      "withIosSceneLifecycle: could not find the window/startReactNative block in AppDelegate.swift. " +
        "The template may have changed; update plugins/withIosSceneLifecycle.js or remove it if expo now " +
        "ships UIScene support.",
    );
  }

  return withConformance.replace(
    windowBlock,
    "    // The window is created and React Native is started by `SceneDelegate` under the\n" +
      "    // scene-based life cycle (required by the iOS 27 SDK). See plugins/withIosSceneLifecycle.js.\n",
  );
}

const withIosSceneLifecycle = (config) => {
  config = withAppDelegate(config, (config) => {
    if (expoShipsSceneSupport(config.modRequest.projectRoot)) {
      return config;
    }
    config.modResults.contents = rewriteAppDelegate(config.modResults.contents);
    return config;
  });

  config = withInfoPlist(config, (config) => {
    if (expoShipsSceneSupport(config.modRequest.projectRoot)) {
      return config;
    }
    config.modResults.UIApplicationSceneManifest = SCENE_MANIFEST;
    return config;
  });

  config = withXcodeProject(config, (config) => {
    const { projectRoot, projectName, platformProjectRoot } = config.modRequest;
    if (expoShipsSceneSupport(projectRoot)) {
      return config;
    }

    fs.writeFileSync(
      path.join(platformProjectRoot, projectName, SCENE_DELEGATE_FILE),
      SCENE_DELEGATE_SOURCE,
    );

    const relativePath = `${projectName}/${SCENE_DELEGATE_FILE}`;
    if (!config.modResults.hasFile(relativePath)) {
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath: relativePath,
        groupName: projectName,
        project: config.modResults,
      });
    }
    return config;
  });

  return config;
};

module.exports = withIosSceneLifecycle;
