// AUTO-GENERATED by scripts/generate-block-registry.ts — do not edit by hand.
// Run `bun run gen:blocks` after adding or changing a block folder.
import type { BlockEntry } from "./types";
import { meta as ctaBanner } from "./cta-banner/meta";
import { meta as faqSection } from "./faq-section/meta";
import { meta as featureGrid } from "./feature-grid/meta";
import { meta as hero } from "./hero/meta";
import { meta as signInForm } from "./sign-in-form/meta";
import { meta as statRow } from "./stat-row/meta";

/** Blocks collected from client/blocks/*\/meta.ts, sorted by order then id. */
export const BLOCKS: BlockEntry[] = [
  ctaBanner,
  faqSection,
  featureGrid,
  hero,
  signInForm,
  statRow,
].sort((a, b) => a.order - b.order || a.id.localeCompare(b.id));
