/**
 * Shared registry codegen for the folder-per-entry tiers.
 *
 * Two tiers ship as "drop a folder, regenerate" collections:
 *
 *   client/templates/<id>/  → client/templates/registry.generated.ts (SCREEN_TEMPLATES)
 *   client/blocks/<id>/     → client/blocks/registry.generated.ts    (BLOCKS)
 *
 * Both are scanned and rendered identically — only the names differ — so the
 * scan/render/CLI logic lives here once and each `scripts/generate-*-registry.ts`
 * is a thin CLI that supplies a `RegistryTarget`. Keeping one implementation
 * means the two committed files can't drift in shape, header, or `--check`
 * behavior.
 *
 * The generated file imports each `meta` from its folder so the output stays
 * type-checked (a malformed `meta.ts` fails `tsc`, not just this script).
 * Entries are sorted by `meta.order` then `id` for a stable grid order and
 * deterministic codegen output.
 */

import * as fs from "fs";
import * as path from "path";

export interface RegistryTarget {
  /** Absolute path of the folder holding `<id>/meta.ts` entry folders. */
  entriesDir: string;
  /** Absolute path of the committed file to write. */
  outputFile: string;
  /** Repo-relative path of the CLI that owns the output, used in the header. */
  generatorPath: string;
  /** Package script that regenerates the output, e.g. `gen:templates`. */
  packageScript: string;
  /** Singular noun for messages, e.g. `template` ("...a template folder"). */
  entryNoun: string;
  /** Plural noun for log counts, e.g. `templates` ("(17 templates)"). */
  entryNounPlural: string;
  /** Entry type imported from `./types`, e.g. `ScreenTemplateEntry`. */
  entryType: string;
  /** Name of the exported array, e.g. `SCREEN_TEMPLATES`. */
  exportName: string;
  /** Sentence-start label for the doc comment, e.g. `Screen templates`. */
  collectionLabel: string;
  /** Repo-relative source dir named in the doc comment, e.g. `client/templates`. */
  sourceDir: string;
}

/** Folder names under `entriesDir` that contain a meta.ts, sorted. */
export function findEntryIds(entriesDir: string): string[] {
  return fs
    .readdirSync(entriesDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) => fs.existsSync(path.join(entriesDir, name, "meta.ts")))
    .sort();
}

/** Identifier-safe alias for an entry id (e.g. "card-grid" → "cardGrid"). */
export function toIdent(id: string): string {
  return id.replace(/[-_](.)/g, (_, c: string) => c.toUpperCase());
}

export function renderRegistry(target: RegistryTarget, ids: string[]): string {
  const imports = ids
    .map((id) => `import { meta as ${toIdent(id)} } from "./${id}/meta";`)
    .join("\n");
  const entries = ids.map((id) => `  ${toIdent(id)},`).join("\n");

  return `// AUTO-GENERATED by ${target.generatorPath} — do not edit by hand.
// Run \`bun run ${target.packageScript}\` after adding or changing a ${target.entryNoun} folder.
import type { ${target.entryType} } from "./types";
${imports}

/** ${target.collectionLabel} collected from ${target.sourceDir}/*\\/meta.ts, sorted by order then id. */
export const ${target.exportName}: ${target.entryType}[] = [
${entries}
].sort((a, b) => a.order - b.order || a.id.localeCompare(b.id));
`;
}

/**
 * Write (or, with `--check`, verify) the target's generated registry.
 *
 * `--check` is the CI drift guard: it exits 1 when the committed
 * file doesn't match what a fresh scan would produce.
 */
export function runRegistryCli(
  target: RegistryTarget,
  argv: string[],
  projectRoot: string,
): void {
  const check = argv.includes("--check");
  const ids = findEntryIds(target.entriesDir);
  const next = renderRegistry(target, ids);
  const outputName = path.basename(target.outputFile);

  if (check) {
    const current = fs.existsSync(target.outputFile)
      ? fs.readFileSync(target.outputFile, "utf8")
      : "";
    if (current !== next) {
      console.error(
        `${outputName} is stale. Run \`bun run ${target.packageScript}\` and commit.`,
      );
      process.exit(1);
    }
    console.log(`${outputName} is up to date (${ids.length} ${target.entryNounPlural}).`);
    return;
  }

  fs.writeFileSync(target.outputFile, next);
  console.log(
    `Wrote ${path.relative(projectRoot, target.outputFile)} (${ids.length} ${target.entryNounPlural}).`,
  );
}
