/**
 * Unit tests for the shared registry codegen.
 *
 * `scripts/lib/registryCodegen.ts` backs both folder-per-entry tiers
 * (`client/templates` → SCREEN_TEMPLATES, `client/blocks` → BLOCKS). Two
 * things need guarding:
 *
 *   1. The pure scan/render helpers, exercised against temp fixtures — a
 *      folder without `meta.ts` must be skipped, output must be sorted, and
 *      each target's header/type/export names must come from its own config.
 *   2. That the *committed* generated files still match a fresh render. This
 *      is the same assertion `gen:*:check` makes, run inside the suite so a
 *      hand-edited registry fails `bun run test:ci` too, not just the hook.
 */

import * as fs from "fs";
import * as os from "os";
import * as path from "path";

import { BLOCK_REGISTRY } from "../generate-block-registry";
import { TEMPLATE_REGISTRY } from "../generate-template-registry";
import {
  findEntryIds,
  renderRegistry,
  runRegistryCli,
  toIdent,
  type RegistryTarget,
} from "../lib/registryCodegen";

const PROJECT_ROOT = path.resolve(__dirname, "..", "..");

/** A throwaway entries dir with one folder per `[id, hasMeta]` pair. */
function makeFixture(entries: [id: string, hasMeta: boolean][]): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "registry-codegen-"));
  for (const [id, hasMeta] of entries) {
    fs.mkdirSync(path.join(dir, id), { recursive: true });
    if (hasMeta) fs.writeFileSync(path.join(dir, id, "meta.ts"), "export const meta = {};\n");
  }
  return dir;
}

function fixtureTarget(entriesDir: string): RegistryTarget {
  return {
    entriesDir,
    outputFile: path.join(entriesDir, "registry.generated.ts"),
    generatorPath: "scripts/generate-fixture-registry.ts",
    packageScript: "gen:fixtures",
    entryNoun: "fixture",
    entryNounPlural: "fixtures",
    entryType: "FixtureEntry",
    exportName: "FIXTURES",
    collectionLabel: "Fixtures",
    sourceDir: "client/fixtures",
  };
}

describe("toIdent", () => {
  it("camel-cases kebab and snake ids so they can be import aliases", () => {
    expect(toIdent("hero")).toBe("hero");
    expect(toIdent("feature-grid")).toBe("featureGrid");
    expect(toIdent("sign-in-form")).toBe("signInForm");
    expect(toIdent("stat_row")).toBe("statRow");
  });

  it("leaves an already-valid identifier untouched", () => {
    expect(toIdent("statRow")).toBe("statRow");
  });
});

describe("findEntryIds", () => {
  it("returns only folders that contain a meta.ts, sorted", () => {
    const dir = makeFixture([
      ["zulu", true],
      ["alpha", true],
      ["no-meta", false],
      ["mike", true],
    ]);

    expect(findEntryIds(dir)).toEqual(["alpha", "mike", "zulu"]);
  });

  it("ignores loose files next to the entry folders", () => {
    const dir = makeFixture([["alpha", true]]);
    fs.writeFileSync(path.join(dir, "types.ts"), "export type X = 1;\n");
    fs.writeFileSync(path.join(dir, "registry.generated.ts"), "");

    expect(findEntryIds(dir)).toEqual(["alpha"]);
  });

  it("returns an empty list for a dir with no entry folders", () => {
    expect(findEntryIds(makeFixture([]))).toEqual([]);
  });
});

describe("renderRegistry", () => {
  it("names the owning generator and script in the do-not-edit header", () => {
    const output = renderRegistry(BLOCK_REGISTRY, ["hero"]);

    expect(output.startsWith("// AUTO-GENERATED by scripts/generate-block-registry.ts")).toBe(true);
    expect(output).toContain("do not edit by hand");
    expect(output).toContain("Run `bun run gen:blocks` after adding or changing a block folder.");
  });

  it("imports each meta by a camel-cased alias and lists it in the export", () => {
    const output = renderRegistry(BLOCK_REGISTRY, ["feature-grid", "sign-in-form"]);

    expect(output).toContain('import { meta as featureGrid } from "./feature-grid/meta";');
    expect(output).toContain('import { meta as signInForm } from "./sign-in-form/meta";');
    expect(output).toContain("export const BLOCKS: BlockEntry[] = [\n  featureGrid,\n  signInForm,\n]");
  });

  it("sorts at runtime by order then id, so meta drives the grid order", () => {
    expect(renderRegistry(BLOCK_REGISTRY, ["hero"])).toContain(
      ".sort((a, b) => a.order - b.order || a.id.localeCompare(b.id));",
    );
  });

  it("takes the entry type and export name from the target, not the tier", () => {
    const templates = renderRegistry(TEMPLATE_REGISTRY, ["hero"]);

    expect(templates).toContain('import type { ScreenTemplateEntry } from "./types";');
    expect(templates).toContain("export const SCREEN_TEMPLATES: ScreenTemplateEntry[]");
    // `*\/` in the emitted comment: the glob can't close the doc comment.
    expect(templates).toContain("Screen templates collected from client/templates/*\\/meta.ts");
    expect(templates).not.toContain("BlockEntry");
  });

  it("is deterministic for the same ids", () => {
    const ids = ["hero", "stat-row"];
    expect(renderRegistry(BLOCK_REGISTRY, ids)).toBe(renderRegistry(BLOCK_REGISTRY, ids));
  });
});

describe("runRegistryCli", () => {
  // The CLI logs its result; silence it repo-wide for this block so the suite
  // output stays readable. `process.exit` is stubbed per-test where relevant —
  // note that a stubbed exit does NOT stop execution, so the code after the
  // `--check` failure branch still runs.
  beforeEach(() => {
    jest.spyOn(console, "log").mockImplementation(() => {});
    jest.spyOn(console, "error").mockImplementation(() => {});
  });

  it("writes the rendered registry to the target's output file", () => {
    const dir = makeFixture([["alpha", true], ["beta", true]]);
    const target = fixtureTarget(dir);

    runRegistryCli(target, ["node", "gen"], PROJECT_ROOT);

    expect(fs.readFileSync(target.outputFile, "utf8")).toBe(
      renderRegistry(target, ["alpha", "beta"]),
    );
  });

  it("--check passes without rewriting a file that is already fresh", () => {
    const dir = makeFixture([["alpha", true]]);
    const target = fixtureTarget(dir);
    const exit = jest.spyOn(process, "exit").mockImplementation((() => {}) as never);

    runRegistryCli(target, ["node", "gen"], PROJECT_ROOT);
    const written = fs.statSync(target.outputFile).mtimeMs;
    runRegistryCli(target, ["node", "gen", "--check"], PROJECT_ROOT);

    expect(exit).not.toHaveBeenCalled();
    expect(fs.statSync(target.outputFile).mtimeMs).toBe(written);
  });

  it("--check exits 1 and names the regen script when a new folder is unregistered", () => {
    const dir = makeFixture([["alpha", true]]);
    const target = fixtureTarget(dir);
    const error = jest.spyOn(console, "error");
    const exit = jest.spyOn(process, "exit").mockImplementation((() => {}) as never);

    runRegistryCli(target, ["node", "gen"], PROJECT_ROOT);
    fs.mkdirSync(path.join(dir, "beta"));
    fs.writeFileSync(path.join(dir, "beta", "meta.ts"), "export const meta = {};\n");
    runRegistryCli(target, ["node", "gen", "--check"], PROJECT_ROOT);

    expect(exit).toHaveBeenCalledWith(1);
    expect(error).toHaveBeenCalledWith(
      "registry.generated.ts is stale. Run `bun run gen:fixtures` and commit.",
    );
  });

  it("--check exits 1 when the output file does not exist at all", () => {
    const target = fixtureTarget(makeFixture([["alpha", true]]));
    const exit = jest.spyOn(process, "exit").mockImplementation((() => {}) as never);

    runRegistryCli(target, ["node", "gen", "--check"], PROJECT_ROOT);

    expect(exit).toHaveBeenCalledWith(1);
  });
});

describe("the committed registries match a fresh render", () => {
  // Same assertion as `gen:templates:check` / `gen:blocks:check`, so a
  // hand-edited registry fails the test suite and not only the git hook.
  it.each([
    ["client/templates/registry.generated.ts", TEMPLATE_REGISTRY],
    ["client/blocks/registry.generated.ts", BLOCK_REGISTRY],
  ])("%s is up to date", (_label, target) => {
    const expected = renderRegistry(target, findEntryIds(target.entriesDir));
    expect(fs.readFileSync(target.outputFile, "utf8")).toBe(expected);
  });

  it("points each target at the tier it owns", () => {
    expect(path.relative(PROJECT_ROOT, TEMPLATE_REGISTRY.entriesDir)).toBe(
      path.join("client", "templates"),
    );
    expect(path.relative(PROJECT_ROOT, BLOCK_REGISTRY.entriesDir)).toBe(
      path.join("client", "blocks"),
    );
  });
});
