#!/usr/bin/env npx tsx
/**
 * Template registry generator.
 *
 * Scans `client/templates/<id>/meta.ts` and writes
 * `client/templates/registry.generated.ts` — a committed barrel that
 * `client/showcase/registry.ts` re-exports as `SCREEN_TEMPLATES`. This makes
 * adding/removing a screen template a one-folder change: drop a folder with a
 * `meta.ts`, run `bun run gen:templates`, done.
 *
 * The generated file imports each `meta` from its folder so the output stays
 * type-checked (a malformed `meta.ts` fails `tsc`, not just this script). Entries
 * are sorted by `meta.order` then `id` for a stable grid order and deterministic
 * codegen output.
 *
 * Usage:
 *   bun run gen:templates          # write the file
 *   bun run gen:templates --check  # exit 1 if the file is stale (CI guard)
 */

import * as fs from "fs";
import * as path from "path";

const PROJECT_ROOT = path.resolve(__dirname, "..");
const TEMPLATES_DIR = path.join(PROJECT_ROOT, "client", "templates");
const OUTPUT_FILE = path.join(TEMPLATES_DIR, "registry.generated.ts");

/** Folder names under client/templates that contain a meta.ts, sorted. */
export function findTemplateIds(templatesDir: string): string[] {
  return fs
    .readdirSync(templatesDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) => fs.existsSync(path.join(templatesDir, name, "meta.ts")))
    .sort();
}

/** Identifier-safe alias for a template id (e.g. "card-grid" → "cardGrid"). */
export function toIdent(id: string): string {
  return id.replace(/[-_](.)/g, (_, c: string) => c.toUpperCase());
}

export function renderRegistry(ids: string[]): string {
  const imports = ids
    .map((id) => `import { meta as ${toIdent(id)} } from "./${id}/meta";`)
    .join("\n");
  const entries = ids.map((id) => `  ${toIdent(id)},`).join("\n");

  return `// AUTO-GENERATED by scripts/generate-template-registry.ts — do not edit by hand.
// Run \`bun run gen:templates\` after adding or changing a template folder.
import type { ScreenTemplateEntry } from "./types";
${imports}

/** Screen templates collected from client/templates/*\\/meta.ts, sorted by order then id. */
export const SCREEN_TEMPLATES: ScreenTemplateEntry[] = [
${entries}
].sort((a, b) => a.order - b.order || a.id.localeCompare(b.id));
`;
}

function main() {
  const check = process.argv.includes("--check");
  const ids = findTemplateIds(TEMPLATES_DIR);
  const next = renderRegistry(ids);

  if (check) {
    const current = fs.existsSync(OUTPUT_FILE)
      ? fs.readFileSync(OUTPUT_FILE, "utf8")
      : "";
    if (current !== next) {
      console.error(
        "registry.generated.ts is stale. Run `bun run gen:templates` and commit.",
      );
      process.exit(1);
    }
    console.log(`registry.generated.ts is up to date (${ids.length} templates).`);
    return;
  }

  fs.writeFileSync(OUTPUT_FILE, next);
  console.log(`Wrote ${path.relative(PROJECT_ROOT, OUTPUT_FILE)} (${ids.length} templates).`);
}

if (require.main === module) {
  main();
}
